services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginxEduphishing
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: phpEduphishing
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      -  ./:/var/www/html

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
