services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginxEduphishing
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: phpEduphishing
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      -  ./:/var/www/html
  
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: bancoEduphishing
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduphishing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
